# Generated by Django 5.0.3 on 2024-09-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('surname', models.CharField(max_length=25)),
                ('bio', models.TextField()),
                ('salary', models.IntegerField(default=0)),
                ('start_work_time', models.TimeField()),
                ('end_work_time', models.TimeField()),
            ],
        ),
    ]
